FakeIG/Models/Post.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FakeIG.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public System.Guid PostID { get; set; }
        public System.Guid MemberID { get; set; }
        public Nullable<System.Guid> PointID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime LastEditTime { get; set; }
        public string Contents { get; set; }
    }
}

FakeIG/Controllers/MainController.cs
using FakeIG.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FakeIG.Const;
using FakeIG.Managers;

namespace FakeIG.Controllers
{
    [Authorize]
    public class MainController : Controller
    {
        private FakeIGEntities2 _db = new FakeIGEntities2();
        private int _pageSize = consts.pageSize;
        private PostManager _pm = new PostManager();
        // GET: Main
        public ActionResult Index()
        {
            Member member = (Member)Session["Member"];
            if (member == null)
            {
                return View("Login", "Member");
            }
            // 找最近更新的文章
            //var postList = _db.Post
            //    .OrderByDescending(m => m.CreateTime)
            //    .Take(_pageSize).ToList();
            var PAMList = _pm.DisplayPostList(member, _pageSize);
            var mm = new MainModel()
            {
                PAMList = PAMList,
                Member = member
            };
            return View(mm);
        }
    }
}

FakeIG/Controllers/PostController.cs
using FakeIG.Managers;
using FakeIG.Models;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace FakeIG.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private FakeIGEntities2 _db = new FakeIGEntities2();
        private PostManager _pm = new PostManager();

        // GET: Post
        public ActionResult Create()
        {
            Member member = (Member)Session["Member"];
            ViewBag.Member = member;

            return View();
        }

        /// <summary> 上傳圖片後新增文章 /// </summary>
        /// <param name="contents"></param>
        /// <param name="imgpath"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Create(string contents, string imgpath)
        {
            Member member = (Member)Session["Member"];
            ViewBag.Member = member;

            var post = new Post()
            {
                PostID = Guid.NewGuid(),
                MemberID = member.MemberID,
                PointID = null,
                CreateTime = DateTime.Now,
                LastEditTime = DateTime.Now,
                Contents = contents,
            };
            _db.Post.Add(post);

            string[] path = imgpath.Split(';');
            foreach (var item in path)
            {
                var imagepath = new ImagePath()
                {
                    ImgPath = item,
                    PostID = post.PostID,
                };
                _db.ImagePath.Add(imagepath);
            }

            _db.SaveChanges();

            return RedirectToAction("Display", new { postID = post.PostID });
        }

        /// <summary> 上傳圖片/// </summary>
        /// <param name="photo"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CreateImg(HttpPostedFileBase[] photo)
        {
            // 先檢查檔案是否為圖檔
            foreach (var item in photo)
            {
                if (this.CheckImgFormat(item.FileName) == false)
                {
                    ViewBag.Msg = "請上傳圖檔";
                    return View("Create");
                }
            }

            // Azure 儲存體金鑰
            CloudStorageAccount storageAccount = CloudStorageAccount.Parse("DefaultEndpointsProtocol=https;AccountName=fakeiguser;AccountKey=QY0XKemcjtZhdeArIGo4LBoNha2VMdEfGorAIdKv9C+wKYuscYTeK1+6GDkJQHJ+75Gto0kYB6SP+AStcdPcIw==;EndpointSuffix=core.windows.net");

            // Create the blob client.
            CloudBlobClient blobClient = storageAccount.CreateCloudBlobClient();

            // Retrieve a reference to a container. 
            CloudBlobContainer container = blobClient.GetContainerReference("fakeiguser");

            // Create the container if it doesn't already exist.
            container.CreateIfNotExists();

            container.SetPermissions(
                     new BlobContainerPermissions
                     {
                         PublicAccess =
                             BlobContainerPublicAccessType.Blob
                     });

            // ---------------------------------------------
            // 上傳圖檔名稱
            string fileName = "";
            Random random = new Random((int)DateTime.Now.Ticks);
            Member member = (Member)Session["Member"];
            ViewBag.Member = member;

            //string folderPath = Const.consts.folderPath;
            //folderPath = HostingEnvironment.MapPath(folderPath);
            List<string> ImgPath = new List<string>();
            for (int i = 0; i < photo.Length; i++)
            {
                HttpPostedFileBase f = photo[i];
                if (f != null)
                {
                    if (f.ContentLength > 0)
                    {
                        /*if (!Directory.Exists(folderPath)) // 假如資料夾不存在，先建立
                            Directory.CreateDirectory(folderPath);
                        fileName = "P" + DateTime.Now.ToString("yyyyMMdd_HHmmss_FFFFFF") + "_" + member.Account + "_" + random.Next(100000).ToString("00000") + Path.GetExtension(f.FileName);
                        var path = Path.Combine(Server.MapPath($"{folderPath}"), fileName);
                        f.SaveAs(path);

                        var viewPath = Path.Combine(folderPath, fileName);
                        ImgPath.Add(viewPath); */

                        // --------------------------------------------------------------------------

                        fileName = "P" + DateTime.Now.ToString("yyyyMMdd_HHmmss_FFFFFF") + "_" + member.Account + "_" + random.Next(100000).ToString("00000");

                        CloudBlockBlob blockBlob = container.GetBlockBlobReference(fileName);

                        blockBlob.Properties.ContentType = f.ContentType;
                        blockBlob.UploadFromStream(f.InputStream);

                        var ImgblockBlob = blockBlob.Uri.AbsoluteUri;

                        ImgPath.Add(ImgblockBlob);
                    }
                }
            }
            ViewBag.ImgPath = ImgPath;
            return View("Create");
        }

        public ActionResult Display(Guid postID)
        {
            Member member = (Member)Session["Member"];
            ViewBag.Member = member;


            var PAM = _pm.DisplayPost(member, postID);
            MainModel mm = new MainModel()
            {
                PAM = PAM,
                Member = member
            };
            return View(mm);
        }

        public ActionResult Reply(Guid pointID, string reply, Guid postMemberID)
        {
            Member member = (Member)Session["Member"];

            // 新增回覆
            var pointPost = new Post()
            {
                PostID = Guid.NewGuid(),
                PointID = pointID,
                MemberID = member.MemberID,
                CreateTime = DateTime.Now,
                LastEditTime = DateTime.Now,
                Contents = reply,
            };
            _db.Post.Add(pointPost);

            // 新增回覆通知
            var replyList = new ReplyList()
            {
                PostID = pointPost.PostID,
                MemberID = member.MemberID,
                PostMemberID = postMemberID,
                Readed = false,
            };
            _db.ReplyList.Add(replyList);

            _db.SaveChanges();
            return RedirectToAction("Display", new { postID = pointPost.PointID });
        }

        [HttpPost]
        public string Like(Guid memberID, Guid postID, Guid postMemberID)
        {
            // 查詢是否有nice紀錄
            var kiroku = _db.NiceList.Where(m => m.MemberID == memberID && m.PostID == postID).FirstOrDefault();
            if (kiroku == null)
            {
                // 沒有就新增一筆
                var nice = new NiceList()
                {
                    MemberID = memberID,
                    PostID = postID,
                    PostMemberID = postMemberID,
                    Yes = true,
                    Readed = false,
                };
                _db.NiceList.Add(nice);
                _db.SaveChanges();

                return "Nice";
            }
            else if (kiroku.Yes == false)
            {
                kiroku.Yes = true;
                _db.Entry(kiroku).CurrentValues.SetValues(kiroku);
                _db.SaveChanges();

                return "Nice";
            }
            else
            {
                kiroku.Yes = false;
                _db.Entry(kiroku).CurrentValues.SetValues(kiroku);
                _db.SaveChanges();

                return "NoNice";
            }
        }

        public ActionResult ToastsReply(Guid memberID)
        {
            var replyList = _db.ReplyList.Where(m => m.PostMemberID == memberID && m.Readed == false).ToList();
            var pointList = _db.Post.Where(m => m.PointID != null).ToList();
            List<PostAndMember> toastsList = new List<PostAndMember>();
            if (replyList.Count > 0)
            {
                for (int i = 0; i < replyList.Count; i++)
                {
                    // 找到回文
                    var post = pointList.Find(m => m.PostID == replyList[i].PostID);
                    // 找到回文者暱稱及圖片
                    var postMember = _db.Member.ToList().Where(m => m.MemberID == replyList[i].MemberID).FirstOrDefault();
                    // 整合回文、回文帳號暱稱及圖片
                    var PostPAM = new PostAndMember()
                    {
                        PostID = post.PostID,
                        PointID = post.PointID,
                        MemberID = post.MemberID,
                        CreateTime = post.CreateTime,
                        LastEditTime = post.LastEditTime,
                        Contents = post.Contents,
                        Name = postMember.Name,
                        PicPath = postMember.PicPath,
                    };
                    toastsList.Add(PostPAM);

                    // 未讀的通知改為已通知
                    replyList[i].Readed = true;
                    _db.Entry(replyList[i]).CurrentValues.SetValues(replyList[i]);
                }

                _db.SaveChanges();
                //ViewBag.replyList = toastsList;
                string jsonText = JsonConvert.SerializeObject(toastsList);
                return Json(toastsList);
            }
            return null;
        }

        public ActionResult ToastsNice(Guid memberID)
        {
            var niceList = _db.NiceList.Where(m => m.PostMemberID == memberID && m.Readed == false).ToList();
            List<PostAndMember> toastsList = new List<PostAndMember>();
            if (niceList.Count > 0)
            {
                for (int i = 0; i < niceList.Count; i++)
                {
                    // 找到按讚者暱稱及圖片

FakeIG/Views/Post/Create.cshtml
@model FakeIG.Models.Post

@{
    ViewBag.Title = "Create";
}

<h2>新貼文</h2>
@{
    if (ViewBag.ImgPath == null)
    {

    <form class="form-horizontal" method="post" action="/Post/CreateImg" enctype="multipart/form-data">
        <div>
            <p>上傳檔案 1:<input type="file" name="photo" /></p>
            <p>上傳檔案 2:<input type="file" name="photo" /></p>
            <p>上傳檔案 3:<input type="file" name="photo" /></p>
            <input type="submit" value="檔案上傳" />
        </div>
        @{ if (ViewBag.Msg != null)
            {
                <p>@ViewBag.Msg</p>
            }

        }
    </form>
    }
    if (ViewBag.ImgPath != null)
    {
        @*<div class="img-thumbnail">
                @foreach (var item in ViewBag.ImgPath)
                {
                    <img src="@item" class="img-responsive" />
                }
            </div>*@
        <div id="carouselExampleIndicators" class="carousel slide col-6 col-md-6 col-lg-6" data-bs-ride="carousel">
            <div class="carousel-indicators">
                @for (int i = 0; i < ViewBag.ImgPath.Count; i++)
                {
                    if (i == 0)
                    {
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="@i" class="active" aria-current="true" aria-label="Slide @i"></button>
                    }
                    else
                    {
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="@i" aria-current="true" aria-label="Slide @i"></button>
                    }
                }
            </div>
            <div class="carousel-inner">
                @for (int i = 0; i < ViewBag.ImgPath.Count; i++)
                {

                    if (i == 0)
                    {
                        <div class="carousel-item active">
                            <img src="@ViewBag.ImgPath[i]" class="d-block w-100" alt="...">
                        </div>
                    }
                    else
                    {
                        <div class="carousel-item">
                            <img src="@ViewBag.ImgPath[i]" class="d-block w-100" alt="...">
                        </div>
                    }
                }
            </div>
            @{
                if (ViewBag.ImgPath.Count != 1)
                {
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                }
            }
        </div>
        using (Html.BeginForm("Create", "Post"))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                <div class="form-group">
                    @Html.LabelFor(model => model.Contents, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <textarea name="contents" placeholder="輸入內文" cols="500" rows="10"></textarea>
                    </div>
                </div>
                @{
                    string path = "";
                    if (ViewBag.ImgPath != null)
                    {

                        for (int i = 0; i < @ViewBag.ImgPath.Count; i++)
                        {
                            if ((i + 1) == @ViewBag.ImgPath.Count)
                            {
                                path += @ViewBag.ImgPath[i];
                            }
                            else
                            {
                                path += @ViewBag.ImgPath[i] + ";";
                            }
                        }
                        <input type="hidden" name="imgpath" value="@path" />
                    }
                }

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="新增" class="btn btn-dark" />
                    </div>
                </div>
            </div>
        }
    }
}


<div>
    @Html.ActionLink("返回首頁", "Index", "Main")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FakeIG/Views/Post/Display.cshtml
@model FakeIG.Models.MainModel

@{
    ViewBag.Title = "Display";
}

<br />
<div class="row">
    <div class="col-12 col-md-6 col-sm-8">
        <div id="carouselExampleIndicators" class="carousel slide carousel-fade" data-bs-ride="carousel" style="height:585px;">
            <div class="carousel-indicators">
                @for (int i = 0; i < Model.PAM.ImgPathList.Count; i++)
                {
                    if (i == 0)
                    {
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="@i" class="active" aria-current="true" aria-label="Slide @i"></button>
                    }
                    else
                    {
                        <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="@i" aria-current="true" aria-label="Slide @i"></button>
                    }
                }
            </div>
            <div class="carousel-inner" style="height:585px;">
                @for (int i = 0; i < Model.PAM.ImgPathList.Count; i++)
                {

                    if (i == 0)
                    {
                        <div class="carousel-item active">
                            <img src="@Model.PAM.ImgPathList[i].ImgPath" alt="..." style="max-width: 100%; max-height: 100%;">
                        </div>
                    }
                    else
                    {
                        <div class="carousel-item">
                            <img src="@Model.PAM.ImgPathList[i].ImgPath" alt="..." style="max-width: 100%; max-height: 100%;">
                        </div>
                    }
                }
            </div>
            @{
                if (Model.PAM.ImgPathList.Count != 1)
                {
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                }
            }
        </div>
    </div>
    <div class="col-12 col-md-4 col-sm-4" style="float: left; border: 1px solid #515151; margin-left: -15px; position: relative; ">
        <div style="margin-top:10px;">
            <img src="@Model.PAM.PicPath" class="img-circle col-2 col-md-2 picRight" style="height:30px;width:30px;border-radius:50%;" />
            <span>@Model.PAM.Name</span>
        </div>
        <hr />
        <div style="overflow:auto; height:298px; padding-bottom:10px; padding-top:10px;">
            <div class="col-10 col-md-10">
                <img src="@Model.PAM.PicPath" class="img-circle col-2 col-md-2 picRight" style="height: 30px; width: 30px; border-radius: 50%; margin-right: 10px;" />
                <span>@Model.PAM.Name</span>
                <p class="replayContent">@Model.PAM.Contents</p>
                <p class="CreateTime replayContent">@PostHelper.GetDay(@Model.PAM.CreateTime)</p>
            </div>
            @{
                if (Model.PAM.PointList.Count > 0)
                {
                    foreach (var item in Model.PAM.PointList)
                    {
                        <div class="row">
                            <div class="col-9 col-md-9 col-sm-9">
                                <img src="@item.PicPath" class="img-circle col-2 col-md-2 picRight" style="height:30px;width:30px;border-radius:50%;" />
                                <span>@item.Name</span>
                                <p class="replayContent">@item.Contents</p>
                                <p class="CreateTime replayContent">@PostHelper.GetDay(@item.CreateTime)</p>
                                @{ if (item.Nice > 1)
                                    { <span>@item.Nice 個讚</span>}
                                }
                            </div>
                            <div class="col-1 col-md-1 col-sm-1" style="float:left;">
                                <button class="btn" type="button" onclick="likePost('@item.PostID', '@ViewBag.Member.MemberID', '@item.MemberID');">
                                    @{
                                        if (item.Yes == true)
                                        {
                                            <img src="~/Images/favorite.png" width="20" height="20" class="align-bottom" id="@item.PostID" />
                                        }
                                        else
                                        {
                                            <img src="~/Images/like.png" width="20" height="20" class="align-bottom" id="@item.PostID" />
                                        }
                                    }
                                </button>
                            </div>
                        </div>
                    }
                }

            }
        </div>
        <div>
            <button class="btn" type="button" onclick="likePost('@Model.PAM.PostID', '@ViewBag.Member.MemberID', '@Model.PAM.MemberID');">
                @{
                    if (Model.PAM.Yes == true)
                    {
                        <img src="~/Images/favorite.png" id="@Model.PAM.PostID" width="25" height="25" class="align-bottom" />
                    }
                    else
                    {
                        <img src="~/Images/like.png" id="@Model.PAM.PostID" width="25" height="25" class="align-bottom" />
                    }
                }
            </button>
            <button class="btn" type="button" >
                <img src="~/Images/message.png" width="25" height="25" class="align-bottom" for="reply"/>
            </button>
            <button class="btn" type="button">
                <img src="~/Images/share.png" width="25" height="25" class="align-bottom" />
            </button>
        </div>
        <div>
            <p>@Model.PAM.Nice 個讚</p>
        </div>
        <div >
            <a href="/Post/Display?postID=@Model.PAM.PostID">
                <p class="CreateTime">@PostHelper.GetDay(@Model.PAM.CreateTime)</p>
            </a>
        </div>
        <div style="margin-bottom: 10px; margin-left: 10px;">
            <hr />
            <form action="/Post/Reply" method="post" class="reply">
                <div class="input-group mb-3 col-8 col-md-8">
                    <button class="btn btn-outline-secondary" type="button" id="button-addon1">☺</button>
                    <input type="text" class="form-control" name="reply" id="reply" placeholder="留言.." aria-label="" aria-describedby="button-addon1">
                    <input type="hidden" name="pointID" value="@Model.PAM.PostID" />
                    <input type="hidden" name="postMemberID" value="@Model.PAM.MemberID" />
                    <input class="btn" type="submit" value="投稿" style="color:azure" />
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    //const axios = require('axios').default;
    function likePost(postID, memberID, postMemberID) {
        axios.post('/Post/Like/', {
            postID: postID,
            memberID: memberID,
            postMemberID: postMemberID,
            })
            .then(function (res) {
                console.log(res);
                if (res.data == "Nice") {
                    $(`#${postID}`).attr("src", "/Images/favorite.png")
                }
                else {
                    $(`#${postID}`).attr("src", "/Images/like.png")
                }
            })
            .catch(function (err) {
                console.log(err)
            });
    }
    //function likePost(postID, memberID) {
    //    if (postID != null && memberID != null) {
    //        var postData = { postID: postID, memberID: memberID }
    //        $.ajax({
    //            url: "/Post/Like",
    //            method: "POST",
    //            data: postData,
    //            dataType: "json",
    //            success: function (henzi) {
    //                console.log(henzi);
    //            },
    //            error: function (henzi) {
    //                console.log(henzi);
    //                alert("通訊失敗，請聯絡管理員。")
    //            }
    //        });
    //    }
    //}
</script>